---
title: 'T-Cell Fluorescence Oscillation Analysis'
author: "Jing Zhao"
date: "9/25/2018"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Rssa)
library(ggplot2)
library(dplyr)
library(reshape)
library("scales")
library(gridExtra)
library(DescTools)
library("EBImage")
```

## Set analysis parameters 
```{r}
# Set ssa window length
window = 124
# Set lag for autocorrelation
lag = 64
# Threshold R-square value to screen sinusoid curve
threshold = 0.95
# Exposure Time (Frame rate, per ms)
frame_rate = 800
```

## Define Functions
```{r}
# Function: Extract x,y coordiantes from each Header
row.xy <- function(string){
  xx <- strsplit(string,"[.]")[[1]][1]
  yy <- strsplit(string,"[.]")[[1]][2]
  x <- as.numeric(substring(xx,2))
  y <- as.numeric(substring(yy,2))
  return(c(x,y))
}

# Function: Split the rowname column into two columns
split.rowname.xy <- function(df) {
  rowNames <- rownames(df)
  df.xy <- data.frame(t(data.frame(lapply(rowNames, row.xy))))
  names(df.xy) <- c("X","Y")
  df[["X"]] <- df.xy[["X"]]
  df[["Y"]] <- df.xy[["Y"]]
  return(df)
}

# Function: Linear detrend 
lm.detrend <- function(df) {
  names(df) <- "Intensity"
  tt <- seq(1,dim(df)[1],1) * frame_rate/1000
  df[["Time"]] <- tt
  lm.fit <- lm(Intensity ~ Time, df)
  df[["Intensity"]] <- df[["Intensity"]] - predict(lm.fit)
  return(df)
}

# Function: Pixel-wise screening for sinusoid oscillation
sine.screen <- function(ts, per, threshold) {
  # The Period screening criteria !!!
  if ((per < 100) & (per > 8)) {
      acf <- acf(ts, lag.max = lag, plot = FALSE)
      # Extract the acf and time pairs 
      y <- acf$acf[1:lag]   # acf value
      t <- acf$lag[1:lag]   # lag time
  
      # Transfomred linear fit for sinusoid time-series
      df_sine <- data.frame(cbind(y, t, sin(2*pi/per*t), cos(2*pi/per*t)))
      names(df_sine) <- c('y','t','sine', 'cos')
      reslm <- lm(y ~  sine + cos + t * sine + t * cos, data = df_sine)
      # The sinusoid screening criteria !!!
      if (summary(reslm)$r.squared >= threshold) {
        return(per)
      }
      else {
        return(0)
      } 
  }
  else {
      return(0)
  }
}

# Function: Plot time-series with single dataframe
ts_plot <- function (col, title){
  df <- data.frame(col)
  names(df) <- "Intensity"
  tt <- seq(1,dim(df)[1],1)* frame_rate/1000
  df[["Time"]] <- tt
  p1 <- ggplot(df, aes(x=Time, y=Intensity))  + geom_line() + ggtitle(title)
  return(p1)
}

# Function: Pixel-wise screening for sinusoid and plotting the extracted vectors and fitting 
sine.screen.plot <- function(ts, per, threshold, header) {
  acf <- acf(ts, lag.max = lag, plot = FALSE)
  # Extract the acf and time pairs 
  y <- acf$acf[1:lag]   # acf value
  t <- acf$lag[1:lag]   # lag time
  
  # Conducting Fast Fourier Transform (FFT)  
  ssp <- spectrum(ts, plot=FALSE) 

  # Transfomred linear fit for damped sinusoid time-series
  df_sine <- data.frame(cbind(y, t, sin(2*pi/per*t), cos(2*pi/per*t)))
  names(df_sine) <- c('y','t','sine', 'cos')
  reslm <- lm(y ~  sine + cos + t * sine + t * cos, data = df_sine)
  
  # The sinusoid screening criteria !!! 
  if (summary(reslm)$r.squared >= threshold & (per < 100) & (per > 8)) {
    # Plot the spectral periodgram of the subset singal
    df_ssp <- data.frame(cbind(ssp$spec,round(1/ssp$freq,digits = 1)))
    names(df_ssp) <- c('Spec','Period')
    p_spec <- ggplot(df_ssp[4:125,], aes(x=Period, y=Spec)) + geom_bar(stat="identity", color="black") + xlab("Period (Frame)") + ylab("Spectral Density") + ggtitle(paste(header, "Spectral Periodgram,","Period =", signif(per,digits=4)))
    
    # Plot reconstrcuted vector calculated from SSA
    p_uu <- ts_plot(ts, paste(header, "Principal Time-Series"))
    title <- paste(header, "ACF,", "Period =", signif(per,digits=4), ",", "R-square =", toString(signif(summary(reslm)$r.squared,digits = 3)))
    
    df_sine[['y_hat']] <- data.frame(fitted(reslm))

    p_sine <-ggplot(df_sine, aes(x = t)) + geom_point(aes(y=y), shape = 1) + geom_line(aes(y=y_hat, color = "red")) + xlab("Frame") + ylab("ACF") + ggtitle(title)
    grid.arrange(p_uu,p_spec,p_sine,ncol=1)
  } 
}

print.df.info <- function(df1, type_name) {
  # Z dimension
  print(paste("There are", dim(df1)[1]-1,"frames in the", type_name, "imaging."))
  # X - Y dimensions
  colNames <- colnames(df1)
  start_xy <- row.xy(colNames[1])
  end_xy <- row.xy(colNames[length(colNames)])
  print(paste("The x coordinstes range from", start_xy[1], "to", end_xy[1],"."))
  print(paste("The y coordinstes range from", start_xy[2], "to", end_xy[2],"."))
  x_pixels <- end_xy[1] - start_xy[1] + 1
  y_pixels <- end_xy[2] - start_xy[2] + 1
  print(paste("The dimension of image frame is", x_pixels,"*", y_pixels,"."))
}



```

## Imaging Data Loading and Preprocessing 

```{r, warning=FALSE, fig.height = 5, fig.width = 4, fig.align ="center"}
# Load data matrix
df_ROI <- read.csv("Cell-1-Big.csv")       
# Remove first two columns, Header is the pixel coordinate in "x.y"" format
df1_ROI <- df_ROI[,3:dim(df_ROI)[2]]
# Report information of cell imaging dafaframe 
print.df.info(df1_ROI, "cell (ROI + Peripheral)")
cat("\n")

# Copy the dataframe for plotting ROI sum fluorescence image
df_ROI_cp <- df1_ROI[-1,]
df_ROI_sum <- data.frame(t(df_ROI_cp[1,]))
df_ROI_sum[[1]] <- colSums(df_ROI_cp)
df_ROI_sum <- split.rowname.xy(df_ROI_sum)
names(df_ROI_sum) <- c("Sum", "X", "Y")

# Load data matrix
df_BG <- read.csv("BG-1.csv")    
# Remove first two columns, Header is the pixel coordinate in "x.y"" format
df1_BG <- df_BG[,3:dim(df_BG)[2]]
# Report information of background imaging dafaframe 
print.df.info(df1_BG, "background (BG)")

# Stack Cell and BG dataframes together
df1_combined <- cbind(df1_ROI, df1_BG)
df2 <- data.frame(t(df1_combined))

# Extract indicator column
df_indicator <- df2[[1]]
# Remove indicator column from dataframe.
df2 <- df2[,-1]
df2 <- data.frame(t(df2))


```


## ROI Pixel-wise Time-Series Analysis 

```{r, warning=FALSE}
# Make a df for collecting pixel-wise time-series statistics. 
# The seven statistic features are :
#1  Average fluorescent intensity of raw series; 
#2  Standard deviation of fluorescent intensity raw series;
#3  e1 percentage; 
#4  p1; 
#5  e2 percentage; 
#6  p2 
#7  e3 percentage;
#8  p3
#9  e4 percentage;
#10 p4

df_stats <- data.frame(t(df2[1:10,]))
names(df_stats) <- c("I_bar","I_std","E1","P1","E2","P2","E3","P3","E4","P4")
# Set all values to 0
df_stats[] <- 0     
# Calculate the average fluorescence intensity (I_bar)
df_stats[,'I_bar'] <- colMeans(df2) 
# Calculate the standard deviation of fluorescence intensity (I_std)
df_stats[,'I_std'] <- apply(df2, MARGIN = 2, FUN=sd)
# Scan through each pixel
for (i in 1:length(df2)) {
  # First step, linear detrend 
  df_pixel_dt <- lm.detrend(df2[i])
  # Second step, Singular Spectrum Analysis (SSA).  
  s <- ssa(df_pixel_dt[["Intensity"]], L = window, plot=FALSE) 
 
  # Calulate singualr vaules in percentage
  SS_percentage <- s$sigma/sum(s$sigma)
  df_stats[i,'E1'] <- SS_percentage[1] + SS_percentage[2]  # Assign the e1 percentage
  df_stats[i,'E2'] <- SS_percentage[3] + SS_percentage[4]  # Assign the e2 percentage
  df_stats[i,'E3'] <- SS_percentage[5] + SS_percentage[6]  # Assign the e3 percentage
  df_stats[i,'E4'] <- SS_percentage[7] + SS_percentage[8]  # Assign the e4 percentage   
  # Extract the left matrix (time-series)  
  recon <- reconstruct(s, groups = list(c(1:2),c(3:4),c(5:6),c(7:8)))
  F1 <- recon$F1
  F2 <- recon$F2
  F3 <- recon$F3
  F4 <- recon$F4

  per1 <- max(parestimate(s, list(1:2), method = "esprit")$periods)
  per2 <- max(parestimate(s, list(3:4), method = "esprit")$periods)
  per3 <- max(parestimate(s, list(5:6), method = "esprit")$periods)
  per4 <- max(parestimate(s, list(7:8), method = "esprit")$periods)
  
  # Calculate autocorrelation function (ACF) of principal time-series   
 
  df_stats[i,'P1'] <- sine.screen(F1, per1, threshold)              # Assign the p1
  df_stats[i,'P2'] <- sine.screen(F2, per2, threshold)              # Assign the p2
  df_stats[i,'P3'] <- sine.screen(F3, per3, threshold)              # Assign the p3
  df_stats[i,'P4'] <- sine.screen(F4, per4, threshold)              # Assign the p4
}

# Convert Header of df1 into X, Y columns of df_stats
rowNames_stats <- rownames(df_stats)
df.xy <- data.frame(t(data.frame(lapply(rowNames_stats, row.xy))))
names(df.xy) <- c("X","Y")
df_stats[["X"]] <- df.xy[["X"]]
df_stats[["Y"]] <- df.xy[["Y"]]

# Retreive the indicator column 
df_stats[['Indicator']] <- df_indicator

# Round Period values to two digits after decimal point
df_stats[['P1']] <- round(df_stats[['P1']], digits=2)
df_stats[['P2']] <- round(df_stats[['P2']], digits=2)
df_stats[['P3']] <- round(df_stats[['P3']], digits=2)
df_stats[['P4']] <- round(df_stats[['P4']], digits=2)

# Determine the characteristic period for each pixel (maximal period chosen)
df_stats[["Period"]] <- apply(df_stats[,c('P1','P2','P3','P4')], 1, FUN=max)
df_stats[['Period']] <- round(df_stats[['Period']], digits=2)

# Count the number of non-zero terms in each column of df_stats
print("The number of non-zero rows of each column in the statistics dataframe:")
colSums(df_stats[,c(1,2,4,6,8,10,14)] != 0) 

# Show unique values of period
print("The periodic values obtained from analysis are:")
sort(unique(df_stats[["Period"]]))

```

## ROI Heatmap Plotting 

```{r, warning=FALSE, fig.height = 3, fig.width = 4, fig.align ="center"}

# Heatmap plot 
# Make a copy of df_stats for plotting heatmap
df_stats_heatmap <- df_stats[df_stats$Indicator == 1 | df_stats$Indicator == 2, ]

# Cell-1 Periodic value and distribution 
matrix_period <- as.matrix.xtabs(xtabs( Period ~ X+Y, data=df_stats_heatmap))/120
m_period <- abind(matrix_period,matrix_period,matrix_period,along=3)
img_period <- Image(m_period,colormode = 'Grayscale')
img_period_map <- rgbImage(green=img_period)
display(img_period_map, method= 'raster')

# Cut-off background pixel's period value (with Cell outline mask)
df_stats_heatmap[df_stats_heatmap$Indicator == 1,]$Period <- 0

matrix_period <- as.matrix.xtabs(xtabs( Period ~ X+Y, data=df_stats_heatmap))/120
m_period <- abind(matrix_period,matrix_period,matrix_period,along=3)
img_period <- Image(m_period,colormode = 'Grayscale')
img_period_map <- rgbImage(green=img_period)
display(img_period_map, method= 'raster')


# Cell-1 Sum Fluorescence Intensity Image
matrix_sum <- as.matrix.xtabs(xtabs( Sum ~ X+Y, data=df_ROI_sum))
matrix_sum <- normalize(matrix_sum)
m3_sum <- abind(matrix_sum,matrix_sum,matrix_sum,along=3)
img_sum <- Image(m3_sum,colormode='Color')
display(img_sum, method = 'raster', all=TRUE)


#jet.colors = colorRampPalette(c("#000000", "#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00"))
#img_period_map <- colormap(img_period, jet.colors(256))
#y = gblur(img_period_map, sigma=0.6)


# Overlay Cell-1 fluorescence summation image and Periodic values ditribution
#img <- rgbImage(blue=img_sum, green=img_sum+img_period, red=img_sum)
img <- rgbImage(blue=m3_sum, green=m3_sum+m_period, red=m3_sum)
display(img, method = 'raster')


```

```{r, echo = FALSE, eval=FALSE}
# Heatmap plot 

ggplot(data = df_stats_heatmap, aes(x=X, y=Y, fill=Period)) + scale_y_continuous(trans = "reverse") +
  geom_tile() + scale_fill_gradient(low="Black", high="green2", guide = 'legend')  + theme_void()

ggplot(data = df_stats_heatmap, aes(x=X, y=Y, fill=Period)) + scale_y_continuous(trans = "reverse") +
  geom_tile() + scale_fill_gradientn(colours= c("black", "dodgerblue4","dodgerblue3","dodgerblue2", "dodgerblue","deepskyblue" ),
                       values=rescale(c(0, 9, 12, 16,  21, 30)), guide = 'legend')  + theme_void()


ggplot(data = df_stats_heatmap, aes(x=X, y=Y, fill=Period)) + scale_y_continuous(trans = "reverse") +
  geom_tile() + scale_fill_gradientn(colours= c("black", "blue","cyan","green","yellow", "orange","red","red" ),
                       values=rescale(c(0, 9, 12, 16,  21, 30)), guide = 'legend')  + theme_void()


```


## Prepare Dataframe for Plotting the Statistics 

```{r}

# Divide the df_stats into Cellular region and BG region according to indicator
df_stats_Cell <- df_stats[which(df_stats$Indicator == 2),]
df_stats_RI <- df_stats[which(df_stats$Indicator == 1),]
df_stats_BG <- df_stats[which(df_stats$Indicator == 0),]

```

## Plotting Statistics
**Histogram**
```{r, warning=FALSE, fig.height = 4, fig.width = 7,fig.align="center"}

df_cmd <- rbind(df_stats_Cell,df_stats_RI, df_stats_BG)

h1 <- ggplot(df_cmd, aes(x=I_bar))  +
  geom_histogram(data = df_stats_Cell, aes(y=..count../sum(..count..)), colour="blue", fill = "blue", alpha =0.3, binwidth = 10) +
  geom_histogram(data = df_stats_RI, aes(y=..count../sum(..count..)), colour="green", fill = "green", alpha =0.3, binwidth = 10) +
  geom_histogram(data = df_stats_BG, aes(y=..count../sum(..count..)), colour="red", fill = "red", alpha =0.3, binwidth = 10) +
  xlab("Average of Fluorescence Intensity") +
  ylab("Counts Percentage")

h2 <- ggplot(df_cmd, aes(x=I_std))  +
  geom_histogram(data = df_stats_Cell, aes(y=..count../sum(..count..)), colour="blue", fill = "blue", alpha =0.3, binwidth = 2) +
  geom_histogram(data = df_stats_RI, aes(y=..count../sum(..count..)), colour="green", fill = "green", alpha =0.3, binwidth = 2) +
  geom_histogram(data = df_stats_BG, aes(y=..count../sum(..count..)), colour="red", fill = "red", alpha =0.3, binwidth = 2) + 
  xlab("Standard Deviation of Fluorescence Intensity") + 
  ylab("Counts Percentage") +
  scale_x_continuous(limits = c(40, 160))

grid.arrange(h1,h2,ncol=2)

```

**Scatter Plot**
```{r,warning=FALSE, fig.height = 7, fig.width = 7, fig.align="center"}
  
sp1 <- ggplot(df_cmd, aes(y = I_bar, x = E1))  +
  geom_point(data = df_stats_Cell, color = "blue", size=0.5, alpha =0.3) +
  geom_point(data = df_stats_RI, color = "green", size=0.5, alpha =0.3) +
  geom_point(data = df_stats_BG, color = "red", size=0.5, alpha =0.3) +
  xlab("Percentage of Principal Signal 1") + 
  ylab("Average of Fluorescence Intensity") 

sp2 <- ggplot(df_cmd, aes(y = I_bar, x = E2))  +
  geom_point(data = df_stats_Cell, color = "blue", size=0.5, alpha =0.3) +
  geom_point(data = df_stats_RI, color = "green", size=0.5, alpha =0.3) +
  geom_point(data = df_stats_BG, color = "red", size=0.5, alpha =0.3) +
  xlab("Percentage of Principal Signal 2") + 
  ylab("Average of Fluorescence Intensity") 

sp3 <- ggplot(df_cmd, aes(y = I_bar, x = E3))  +
  geom_point(data = df_stats_Cell, color = "blue", size=0.5, alpha =0.3) +
  geom_point(data = df_stats_RI, color = "green", size=0.5, alpha =0.3) +
  geom_point(data = df_stats_BG, color = "red", size=0.5, alpha =0.3) +
  xlab("Percentage of Principal Signal 3") + 
  ylab("Average of Fluorescence Intensity") 

sp4 <- ggplot(df_cmd, aes(y = I_bar, x = E4))  +
  geom_point(data = df_stats_Cell, color = "blue", size=0.5, alpha =0.3) +
  geom_point(data = df_stats_RI, color = "green", size=0.5, alpha =0.3) +
  geom_point(data = df_stats_BG, color = "red", size=0.5, alpha =0.3) +
   xlab("Percentage of Principal Signal 4") + 
  ylab("Average of Fluorescence Intensity") 

grid.arrange(sp1,sp2,sp3,sp4,ncol=2)


```

**Barplot**
```{r, warning=FALSE, fig.height = 4, fig.width = 6, fig.align="center"}

ggplot(df_cmd, aes(x=Period))  + scale_x_continuous(limits = c(8, 120)) + 
  geom_histogram(data = df_stats_Cell, aes(y=..count../sum(..count..)), colour="blue", fill = "blue", alpha =0.4, binwidth = 6) +
  geom_histogram(data = df_stats_RI, aes(y=..count../sum(..count..)), colour="green", fill = "green", alpha =0.4, binwidth = 6) +
  geom_histogram(data = df_stats_BG, aes(y=..count../sum(..count..)), colour="red", fill = "red", alpha =0.4, binwidth = 6) +
  facet_grid(Indicator ~ .) +
  xlab("Period") +
  ylab("Counts Percentage")

```



```{r,warning=FALSE, fig.height = 4, fig.width = 8, fig.ncol=2, fig.align="center"}
# Make a df_stats copy for factors plotting
df_stats_factor <- df_stats

df_stats_factor$Period <- cut(df_stats_factor$Period, c(-1, 7, 20, 40, 60, 80, 105))

df_stats_factor_Cell <- df_stats_factor[which(df_stats_factor$Indicator == 2),]
df_stats_factor_RI <- df_stats_factor[which(df_stats_factor$Indicator == 1),]
df_stats_factor_BG <- df_stats_factor[which(df_stats_factor$Indicator == 0),]

p5 <- ggplot(df_stats_factor_Cell, aes(y = I_bar, x = Period)) + geom_boxplot(fill='blue',alpha=0.6) + scale_y_continuous(limits = c(1100, 1620)) + 
    stat_summary(fun.y=mean, geom="point", shape=5, size=2) + ggtitle("Cell ROI") + ylab("Average of Fluorescence Intensity") + xlab("Period (Frames)")
 
p7 <- ggplot(df_stats_factor_BG, aes(y = I_bar, x = Period)) + geom_boxplot(fill='red',alpha=0.6) + scale_y_continuous(limits = c(1100, 1620)) +
    stat_summary(fun.y=mean, geom="point", shape=5, size=2) + ggtitle("Background") + ylab("Average of Fluorescence Intensity") + xlab("Period (Frames)")

p6 <- ggplot(df_stats_factor_RI, aes(y = I_bar, x = Period)) + geom_boxplot(fill='green',alpha=0.6) + scale_y_continuous(limits = c(1100, 1620)) +
    stat_summary(fun.y=mean, geom="point", shape=5, size=2) + ggtitle("Peripheral") + ylab("Average of Fluorescence Intensity") + xlab("Period (Frames)")

grid.arrange(p5,p6,p7,ncol=3)

p7 <- ggplot(df_stats_factor_Cell, aes(y = I_std, x = Period)) + geom_boxplot(fill='blue',alpha=0.6)  + scale_y_continuous(limits = c(50, 180)) +
    stat_summary(fun.y=mean, geom="point", shape=5, size=2) + ggtitle("Cell ROI") + ylab("Standard Deviation of Fluorescence Intensity") + xlab("Period (Frames)")

p9 <- ggplot(df_stats_factor_BG, aes(y = I_std, x = Period)) + geom_boxplot(fill='red',alpha=0.6) + scale_y_continuous(limits = c(50, 180)) +
    stat_summary(fun.y=mean, geom="point", shape=5, size=2) + ggtitle("Background") + ylab("Standard Deviation of Fluorescence Intensity") + xlab("Period (Frames)")

p8 <- ggplot(df_stats_factor_RI, aes(y = I_std, x = Period)) + geom_boxplot(fill='green',alpha=0.6) + scale_y_continuous(limits = c(50, 180)) +
    stat_summary(fun.y=mean, geom="point", shape=5, size=2) + ggtitle("Peripheral") + ylab("Standard Deviation of Fluorescence Intensity") + xlab("Period (Frames)")

grid.arrange(p7,p8,p9,ncol=3)

```

## Check through all pixels with non-zero period values

```{r, warning=FALSE, fig.height = 4, fig.width = 7, fig.align="center"}
set.seed(15)
df_stats_Cell <- df_stats_Cell[sample(nrow(df_stats_Cell),6),]
df_stats_Cell_sample <- df_stats_Cell[!duplicated(df_stats_Cell[,'Period']),]
df_stats_Cell_sample <- df_stats_Cell_sample[order(-df_stats_Cell_sample$Period),]

for (i in 1:dim(df_stats_Cell_sample)[1]) {
  # For pixel with non-zero period value
  if (df_stats_Cell_sample[i,'Period'] > 0) {  
    header <- rownames(df_stats_Cell_sample)[i]
    # Load single time-series from df1
    df_pixel <- df2[header]
    print(paste("The pixel is", header,",", "Its period is", df_stats_Cell_sample[i,'Period']))
    # Plot raw fluorescent intensity time-series
    p1 <- ts_plot(df_pixel, paste(header, "Raw Fluorescent Intensity Time-Series"))
    # Plot detrend and normalized fluorescent intensity time-series
    df_pixel_dt <- data.frame(lm.detrend(df_pixel))
    p2 <- ts_plot(df_pixel_dt, paste(header, "Linear Detrend Fluorescent Intensity Time Series"))
    # Plot spectrum periodgram of detrend and normalized fluorescent signal (before SSA)
    ssp_dt <- spectrum(df_pixel_dt, plot=FALSE)
    df_ssp_dt <- data.frame(cbind(ssp_dt$spec,round(1/ssp_dt$freq,digits = 1)))
  names(df_ssp_dt) <- c('Spec_density','Period')
    p3 <- ggplot(df_ssp_dt[4:125,], aes(x=Period, y=Spec_density)) + geom_bar(stat="identity", color="black") + ylab("Spectral Density")
    grid.arrange(p1,p2,p3,ncol=1)
    
    s <- ssa(df_pixel_dt, L=window)  
    recon <- reconstruct(s, groups = list(c(1:2), c(3:4),c(5:6),c(7:8)))

    F1 <- recon$F1
    F2 <- recon$F2
    F3 <- recon$F3
    F4 <- recon$F4
    
    per1 <- max(parestimate(s, list(1:2), method = "esprit")$periods)
    per2 <- max(parestimate(s, list(3:4), method = "esprit")$periods)
    per3 <- max(parestimate(s, list(5:6), method = "esprit")$periods)
    per4 <- max(parestimate(s, list(7:8), method = "esprit")$periods)

    # Extract the left matrix (time-series)
    sine.screen.plot(F1, per1, threshold,"F1")
    sine.screen.plot(F2, per2, threshold,"F2")
    sine.screen.plot(F3, per3, threshold,"F3")
    sine.screen.plot(F4, per4, threshold,"F4")
  }
}

```


## Checking Individual Pixel

```{r, echo = FALSE, eval = FALSE}

# Input of pixel header
pixel.header <- "X26.Y60"
# Load single time-series from df1
df_pixel <- df2[pixel.header]

# Plot detrend and normalized fluorescent intensity time-series
df_pixel_dt <- data.frame(lm.detrend(df_pixel))
# FFT of the detrend and normalized fluorescent intensity time-series
ssp_dt <- spectrum(df_pixel_dt[["Intensity"]], plot=FALSE)
# Plot the periodgram (up to 64 frames) of the detrend fluorescent intensity time-series
df_ssp_dt <- data.frame(cbind(ssp_dt$spec,round(1/ssp_dt$freq,digits = 1)))
names(df_ssp_dt) <- c('Spec_density','Period')
ggplot(df_ssp_dt[4:125,], aes(x=Period, y=Spec_density)) + geom_bar(stat="identity", color="black") + ggtitle("Spectral Periodgram of Detrend Fluorescence Signal")

p1 <- ts_plot(df_pixel, "Raw Fluorescent Intensity Time-Series")
p2 <- ggplot(df_pixel_dt, aes(x=Time, y=Intensity))  + geom_line() + ggtitle("Linear Detrend Fluorescent Intensity Time Series")
grid.arrange(p1,p2,ncol=1)

# Conduct SSA
s <- ssa(df_pixel_dt[["Intensity"]], L=window)   

plot(s) # Eigenvalues
plot(s, type = "vectors") # Eigenvectors
plot(s, type = "paired") # Pairs of eigenvectors
plot(wcor(s)) # w-correlation matrix plot

plot(wcor(s, groups = as.list(1:8))) # w-correlation matrix plot

recon <- reconstruct(s, groups = list(c(1:2), c(3:4),c(5:6),c(7:8)))

F1 <- recon$F1
F2 <- recon$F2
F3 <- recon$F3
F4 <- recon$F4
res <- residuals(recon)

pF1<- ts_plot(F1,"F1")
pF2<- ts_plot(F2,"F2")
pF3<- ts_plot(F3,"F3")
pF4<- ts_plot(F4,"F4")
pres <- ts_plot(res,"Residue")

grid.arrange(p2,pF1,pF2, ncol=1)
grid.arrange(p2,pF3,pF4, ncol=1)

per1 <- max(parestimate(s, list(1:2), method = "esprit")$periods)
per1
per11 <- max(parestimate(s, list(1:2), method = "esprit", solve.method = "tls")$periods)
per11

per2 <- max(parestimate(s, list(3:4), method = "esprit")$periods)
per3 <- max(parestimate(s, list(5:6), method = "esprit")$periods)
per4 <- max(parestimate(s, list(7:8), method = "esprit")$periods)


ssp<-spectrum(F1, plot=FALSE)
per_fft_1 <- 1/ssp$freq[ssp$spec==max(ssp$spec)]
ssp<-spectrum(F2, plot=FALSE)
per_fft_2 <- 1/ssp$freq[ssp$spec==max(ssp$spec)]
ssp<-spectrum(F3, plot=FALSE)
per_fft_3 <- 1/ssp$freq[ssp$spec==max(ssp$spec)]
ssp<-spectrum(F4, plot=FALSE)
per_fft_4 <- 1/ssp$freq[ssp$spec==max(ssp$spec)]

# Extract the left matrix (time-series)
sine.screen.plot(F1, per1, 0,"F1")
sine.screen.plot(F2, per2, 0,"F2")
sine.screen.plot(F3, per3, 0,"F3")
sine.screen.plot(F4, per4, 0,"F4")

sine.screen.plot(F1, per_fft_1, 0,"F1")
sine.screen.plot(F2, per_fft_2, 0,"F2")
sine.screen.plot(F3, per_fft_3, 0,"F3")
sine.screen.plot(F4, per_fft_4, 0,"F4")

```









